### ISSUE TITLE
Double List Numbering

### ISSUE THREAD

**Issue by kaileighrose** [learn-co-curriculum/quiz-html-fundamentals#2]
Each item on the quiz is numbered twice.

**Comment by AnnJohn** [comment]
@jongrover can you look at this? 

thanks @kaileighrose for raising the issue

**Comment by jongrover** [comment]
Ya that's because before there were no line numbers on code blocks in Learn, then I added that feature to Learn cause I wanted them. So now we can remove the old line numbers in the quiz answer.

**Comment by jongrover** [comment]
solved!
