### ISSUE TITLE
MOKUP problems

### ISSUE THREAD

**Issue by gemason** [learn-co-curriculum/quiz-html-fundamentals#6]
What does cd in the local repo mean?

**Comment by maxwellbenton** [comment]
Hello @gemason,

To 'cd' into a repo means to navigate to the particular folder, the local version of a git repository, using the terminal command `cd`.  However, I do not see where this is mentioned in this quiz, so for now I am going to close this issue.  Please feel free to reopen an issue if you feel this is not resolved.

Thank you for reaching out!
