### ISSUE TITLE
Missing apostrophe for 'documents HTML version'

### ISSUE THREAD

**Issue by veloblank** [learn-co-curriculum/quiz-html-fundamentals#7]
Should be 'document's HTML version'

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
